language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

addons:
  apt_packages:
  - libcups2-dev
services:
- mysql
install:
- pip install --upgrade pip
- pip install -e git+https://gitlab.com/pycqa/flake8#egg=flake8
- pip install coveralls
- pip install mysqlclient
- pip install -e .
- pip install -q -r requirements.txt
before_script:
- flake8 ambition_auth
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=ambition_auth manage.py test
after_success:
- coveralls
