pii_view = [
    "ambition_screening.view_historicalsubjectscreening",
    "ambition_screening.view_subjectscreening",
    "ambition_subject.view_historicalsubjectconsent",
    "ambition_subject.view_historicalsubjectreconsent",
    "ambition_subject.view_subjectconsent",
    "ambition_subject.view_subjectreconsent",
    "edc_locator.view_historicalsubjectlocator",
    "edc_locator.view_subjectlocator",
    "edc_registration.display_dob",
    "edc_registration.display_firstname",
    "edc_registration.display_identity",
    "edc_registration.display_initials",
    "edc_registration.display_lastname",
    "edc_registration.view_historicalregisteredsubject",
    "edc_registration.view_registeredsubject",
]
